### PR TITLE
Add dm slidedeck

### PR DESCRIPTION
**Pull request by maelle**
Adding @krlmlr's slidedeck. Thank you! :smile_cat:

### CODE REVIEW

**Comment by ivelasq** [comment]
Wonderful, thank you!

**Comment by maelle** [comment]
@ivelasq how could this slidedeck link also appear on https://www.rstudio.com/conference/2022/talks/dm-analyze-build-deploy-relational/? Thank you :pray:

**Comment by ivelasq** [comment]
Hi @maelle ! I've submitted a request to add the link to the deck to the website page! I'll let you know once it's updated. Thank you.

**Comment by maelle** [comment]
Thank _you_!!

**Comment by ivelasq** [comment]
The page is updated, @maelle ! 🙌

**Comment by maelle** [comment]
Thanks so much @ivelasq!!

**Comment by krlmlr** [comment]
Thanks all!

**Pull request merged**
